int v;
int w;
char x[8];
long long y;
fees()
{
cout<<"Enter your semester:-";
cin>>v;
switch(v)
{
case 1:
{cout<<"The fees for 1 semester is:-Rs.64000";
cout<<"\n\nTo pay fees fill the following credentials:-";
cout<<"\nEnter your roll number:-";
cin>>w;
cout<<"\nEnter your branch and section:-";
cin>>x;
cout<<"\nEnter the amount to be paid:-";
cin>>y;
clrscr();
if(y == 64000)
{cout<<w<<" have sucessfully paid the fees.";}
else
{cout<<"Please check the amount you have filled";}
break;}
case 2:
{cout<<"The fees for 2 semester is:-Rs.84000";
cout<<"\n\nTo pay fees fill the following credentials:-";
cout<<"\nEnter your roll number:-";
cin>>w;
cout<<"\nEnter your branch and section:-";
cin>>x;
cout<<"\nEnter the amount to be paid:-";
cin>>y;
clrscr();
if(y == 84000)
{cout<<w<<" have sucessfully paid the fees.";}
else
{cout<<"Please check the amount you have filled";}
break;     }
case 3:
{cout<<"The fees for 3 semester is:-Rs.84000";
cout<<"\n\nTo pay fees fill the following credentials:-";
cout<<"\nEnter your roll number:-";
cin>>w;
cout<<"\nEnter your branch and section:-";
cin>>x;
cout<<"\nEnter the amount to be paid:-";
cin>>y;
clrscr();
if(y == 84000)
{cout<<w<<" have sucessfully paid the fees.";}
else
{cout<<"Please check the amount you have filled";}
break;    }
case 4:
{cout<<"The fees for 4 semester is:-Rs.68000";
cout<<"\n\nTo pay fees fill the following credentials:-";
cout<<"\nEnter your roll number:-";
cin>>w;
cout<<"\nEnter your branch and section:-";
cin>>x;
cout<<"\nEnter the amount to be paid:-";
cin>>y;
clrscr();
if(y == 68000)
{cout<<w<<" have sucessfully paid the fees.";}
else
{cout<<"Please check the amount you have filled";}
break;   }
case 5:
{cout<<"The fees for 5 semester is:-Rs.64000";
cout<<"\n\nTo pay fees fill the following credentials:-";
cout<<"\nEnter your roll number:-";
cin>>w;
cout<<"\nEnter your branch and section:-";
cin>>x;
cout<<"\nEnter the amount to be paid:-";
cin>>y;
clrscr();
if(y == 64000)
{cout<<w<<" have sucessfully paid the fees.";}
else
{cout<<"Please check the amount you have filled";}
break;  }
case 6:
{cout<<"The fees for 6 semester is:-Rs.77000";
cout<<"\n\nTo pay fees fill the following credentials:-";
cout<<"\nEnter your roll number:-";
cin>>w;
cout<<"\nEnter your branch and section:-";
cin>>x;
cout<<"\nEnter the amount to be paid:-";
cin>>y;
clrscr();
if(y == 77000)
{cout<<w<<" have sucessfully paid the fees.";}
else
{cout<<"Please check the amount you have filled";}
break; }
case 7:
{cout<<"The fees for 7 semester is:-Rs.84000";
cout<<"\n\nTo pay fees fill the following credentials:-";
cout<<"\nEnter your roll number:-";
cin>>w;
cout<<"\nEnter your branch and section:-";
cin>>x;
cout<<"\nEnter the amount to be paid:-";
cin>>y;
clrscr();
if(y == 84000)
{cout<<w<<" have sucessfully paid the fees.";}
else
{cout<<"Please check the amount you have filled";}
break;}
case 8:
{cout<<"The fees for 8 semester is:-Rs.64000";
cout<<"\n\nTo pay fees fill the following credentials:-";
cout<<"\nEnter your roll number:-";
cin>>w;
cout<<"\nEnter your branch and section:-";
cin>>x;
cout<<"\nEnter the amount to be paid:-";
cin>>y;
clrscr();
if(y == 64000)
{cout<<w<<" have sucessfully paid the fees.";}
else
{cout<<"Please check the amount you have filled";}
break;}
default:
{cout<<"Please enter valid option";
}
}}